refactored firetrader.js to support tce and multiple eq traders
TheCodeSinger/equibot pull request #26
Opened 2020-09-06 14:26 UTC by Kastang

See Discord for additional details.

2020-09-23 16:54 UTC, TheCodeSinger requested changes

2020-09-23 16:54 UTC, TheCodeSinger commented on commands/firetrade.js
> +  aliases: ['tr', 'trade'],
I don't like the mismatch of the filename now. I'd prefer to either 1. create a new command file called trade.js and delete firetrade.js or rename this one to trade.js.

I don't think the filename always has to match the primary command name, but in this case it's quite a deviation.

2020-09-23 16:54 UTC, TheCodeSinger commented on commands/firetrade.js
> +  const traders = client.config.params.firetrade.traders;
is the `firetrade` prop name a holdover to the old naming? I would think it should just be `client.config.params.traders`

2020-09-23 16:54 UTC, TheCodeSinger commented on commands/firetrade.js
> +          Partial matches found for "${item_name}, use one of the below commands:
fully enclose the var with quotes. You left out the closing quote.   "${item_name}"
Same in line 118, above.

2020-09-23 16:54 UTC, TheCodeSinger commented on commands/firetrade.js
> +    // e.g. `!tr xanex`
lol, your example exact match is wrong. It's "Xanax".

2020-10-07 20:55 UTC, owski commented
Thank you for the suggestions. They were incorporated and `firetrade.js` was renamed to `trade.js`.

Will validate on stage shortly

2020-10-07 20:56 UTC, Kastang commented
Thank you for the suggestions, the latest commit should account for them all.

I will be pushing to stage for a short test before going to production.

2020-10-07 21:00 UTC, TheCodeSinger approved these changes

2020-10-07 21:46 UTC, TheCodeSinger approved these changes

2020-10-07 23:49 UTC, TheCodeSinger approved these changes

2020-10-07 23:49 UTC, merged